
server:
    port: 8081   # web\u5E94\u7528\u670D\u52A1\u7AEF\u53E3
    servlet:
        context-path: /qw

spring:
    thymeleaf:
        cache: false # 启用缓存:建议生产开启

        check-template-location: true # 检查模版是否存在
        enabled: true # 是否启用
        encoding: UTF-8 # 模版编码
        excluded-view-names: # 应该从解析中排除的视图名称列表（用逗号分隔）
        mode: HTML5 # 模版模式
        #        mode: LEGACYHTML5
        classic_compile : true
        suffix: .html # 模版后缀
        prefix: classpath:/templates/ # 模版存放路径

#    freemarker:
#        cache: false # 缓存配置 开发阶段应该配置为false 因为经常会改
#        suffix: .html # 模版后缀名 默认为ftl
#        charset: UTF-8 # 文件编码
#        template-loader-path: classpath:/templates/



#    mvc:
#        view:
#            suffix: .jsp
#            prefix: /WEB-INF/jsp/

debug: true
#
#primarydb:
#    uniqueResourceName: primary
#    xaDataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
#    xaProperties:
#        url: jdbc:mysql://127.0.0.1/test?
#        user: root
#        password: 123456
#    exclusiveConnectionMode: true
#    minPoolSize: 3
#    maxPoolSize: 10
#    testQuery: SELECT 1 from dual #由于采用HikiriCP，用于检测数据库连接是否存活。
#
#secondarydb:
#    uniqueResourceName: secondary
#    xaDataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
#    xaProperties:
#        url: jdbc:mysql://127.0.0.1/test2?
#        user: root
#        password: 123456
#    exclusiveConnectionMode: true
#    minPoolSize: 3
#    maxPoolSize: 10
#    testQuery: SELECT 1 from dual #由于采用HikiriCP，用于检测数据库连接是否存活。

#mybatis:
#    mapper-locations: classpath:generator/*.xml
logging:
    level:
        com.qw.bootlearn: debug





